name = "nonlinearlstr"
uuid = "21ca2098-f897-4540-9ab3-b13ed390dd37"
authors = ["vcantarella <vcantarella@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"

[compat]
LinearAlgebra = "1.11.0"
PythonCall = "0.9.23"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
